  version: 2

sources:
  - name: encounters
    database: map_encounters
    schema: mx_encounters_20220306
    tables:
      - name: aa
        identifier: allowedamounts_ga
      - name: mx
        identifier: encountersmx_ls_ga
      - name: s_lines
        identifier: encountersmx_ls_ga_service_lines
      - name: visits
        identifier: visits_ls_ga
      - name: eligibility
        identifier: eligibilitystatus_ls_ga
  - name: encounters_v1
    database: map_encounters
    schema: mx_encounters_20210104
    tables:
      - name: aa
        identifier: allowedamounts_ga
      - name: mx
        identifier: encountersmx_ls_ga
      - name: s_lines
        identifier: encountersmx_ls_ga_service_lines
      - name: visits
        identifier: visits_ls_ga
      - name: eligibility
        identifier: eligibilitystatus_ls_ga
  - name: encounters_v2
    database: map_encounters
    schema: mx_encounters_20210802
    tables:
      - name: aa
        identifier: allowedamounts_ga
      - name: mx
        identifier: encountersmx_ls_ga
      - name: s_lines
        identifier: encountersmx_ls_ga_service_lines
      - name: visits
        identifier: visits_ls_ga
      - name: eligibility
        identifier: eligibilitystatus_ls_ga
  - name: vocabulary
    database: map_vocabulary
    schema: public
    tables:
      - name: procedure
        identifier: v_procedure
  - name: med_fee
    database: med_physician_fee_schedule
    schema: public
    tables:
      - name: mpfs
        identifier: mpfs
      - name: locality
        identifier: locality